language_pair = {  # nac name : bb name
    "ko-vi": "ko_KR-vi_VN",
    "zh-CN-ja": "zh_CN-ja_JP",
    "zh-TW-en": "zh_TW-en_US",
    "de-fr": "de_DE-fr_FR",
    "es-de": "es_ES-de_DE",
    "de-es": "de_DE-es_ES",
    "zh-CN-vi": "zh_CN-vi_VN",
    "vi-zh-CN": "vi_VN-zh_CN",
    "ko-zh-TW": "ko_KR-zh_TW",
    "ko-ru": "ko_KR-ru_RU",
    "en-pl": "en_US-pl_PL",
    "pl-en": "pl_PL-en_US",
    "ja-en-GB": "ja_JP-en_GB",
    "pt-BR-en-GB": "pt_BR-en_GB",
    "tr-en-GB": "tr_TR-en_GB",
    "ar-en-GB": "ar_AE-en_GB",
    "it-en-GB": "it_IT-en_GB",
    "fr-en-GB": "fr_FR-en_GB",
    "th-en-GB": "th_TH-en_GB",
    "ar-en": "ar_AE-en_US",
    "en-tr": "en_US-tr_TR",
    "tr-en": "tr_TR-en_US",
    "es-en-GB": "es_ES-en_GB",
    "ja-en": "ja_JP-en_US",
    "de-en-GB": "de_DE-en_GB",
    "de-en": "de_DE-en_US",
    "es-en": "es_ES-en_US",
    "vi-en": "vi_VN-en_US",
    "th-en": "th_TH-en_US",
    "id-en": "id_ID-en_US",
    "en-vi": "en_US-vi_VN",
    "en-th": "en_US-th_TH",
    "en-id": "en_US-id_ID",
    "zh-CN-en-GB": "zh_CN-en_GB",
    "zh-CN-ko": "zh_CN-ko_KR",
    "ja-ko": "ja_JP-ko_KR",
    "en-ko": "en_US-ko_KR",
    "zh-CN-en": "zh_CN-en_US",
    "ko-ja": "ko_KR-ja_JP",
    "ko-en": "ko_KR-en_US",
    "ko-zh-CN": "ko_KR-zh_CN",
    "en-ru": "en_US-ru_RU",
    "en-pt-BR": "en_US-pt_BR",
    "en-it": "en_US-it_IT",
    "en-zh-TW": "en_US-zh_TW",
    "en-fr": "en_US-fr_FR",
    "en-es": "en_US-es_ES",
    "en-de": "en_US-de_DE",
    "en-ar": "en_US-ar_AE",
    "en-zh-CN": "en_US-zh_CN",
}

bb_language = [
    "ar_AE",
    "de_DE",
    "en_GB",
    "en_US",
    "es_ES",
    "fr_FR",
    "id_ID",
    "it_IT",
    "ja_JP",
    "ko_KR",
    "pl_PL",
    "pt_BR",
    "ru_RU",
    "th_TH",
    "tr_TR",
    "vi_VN",
    "zh_CN",
    "zh_TW",
]
