[
    {
        "id": 390984,
        "job_id": 98,
        "project_id": 250,
        "sid": "2",
        "content": "Công ty Cổ phần TGKC – Thành viên Tập đoàn DOJI",
        "tr": {
            "g": "TGKC Joint Stock Company – Member of DOJI Group",
            "m": "TGKC Joint Stock Company – Member of DOJI Group"
        },
        "unit_count": 11,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-22T02:16:59.112Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 264885,
            "job_id": 98,
            "source_id": 390984,
            "user_id": 1119094,
            "content": {
                "first_tr": "TGKC Joint Stock Company - A member of DOJI Group",
                "second_tr": "TGKC Joint Stock Company - A subsidiary of DOJI Group"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4336947,
            "created_at": "2023-03-22T02:16:59.100Z",
            "updated_at": null
        }
    },

































    
    {
        "id": 390985,
        "job_id": 98,
        "project_id": 250,
        "sid": "3",
        "content": "Trụ sở chính: 59 Đường số 27, Phường 6, Quận Gò Vấp, Thành phố Hồ Chí Minh, Việt Nam.",
        "tr": {
            "g": "Head office: 59 Street No. 27, Ward 6, Go Vap District, Ho Chi Minh City, Vietnam.",
            "m": "Head Office: 59 Street No. 27, Ward 6, Go Vap District, Ho Chi Minh City, Vietnam."
        },
        "unit_count": 19,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-25T20:10:40.702Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265352,
            "job_id": 98,
            "source_id": 390985,
            "user_id": 4336947,
            "content": {
                "first_tr": "Head office: 59 Street 27, Ward 6, Go Vao District, Ho Chi Minh City, Vietnam.",
                "second_tr": "Headquarter: 59 St. 27, Ward 6, Go Vap District, Ho Chi Minh City, Vietnam."
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-25T20:10:40.698Z",
            "updated_at": null
        }
    },
    {
        "id": 390986,
        "job_id": 98,
        "project_id": 250,
        "sid": "5",
        "content": "BỘ SƯU TẬP TRANG SỨC QUÝ ÔNG",
        "tr": {
            "g": "MEN'S JEWELRY COLLECTION",
            "m": "GENTLEMEN'S JEWELRY COLLECTION"
        },
        "unit_count": 7,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-25T20:09:47.154Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265302,
            "job_id": 98,
            "source_id": 390986,
            "user_id": 4336947,
            "content": {
                "first_tr": "JEWELRY COLLECTION FOR MEN"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-25T20:09:47.143Z",
            "updated_at": null
        }
    },
    {
        "id": 390987,
        "job_id": 98,
        "project_id": 250,
        "sid": "7",
        "content": "Thương hiệu kim cương và trang sức cao cấp hàng đầu Việt nam với hơn 100 cửa hàng trên toàn quốc.",
        "tr": {
            "g": "Vietnam's leading luxury diamond and jewelry brand with more than 100 stores nationwide.",
            "m": "Vietnam's leading diamond and jewelry brand with more than 100 stores nationwide."
        },
        "unit_count": 21,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-26T06:54:19.848Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265392,
            "job_id": 98,
            "source_id": 390987,
            "user_id": 4336947,
            "content": {
                "first_tr": "Vietnam's leading luxury diamond and jewelry brand with over 100 stores nationwide.",
                "second_tr": "The leading high-class diamond and jewelry brand in Vietnam with more than 100 stores nationwide"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-26T06:54:19.844Z",
            "updated_at": null
        }
    },
    {
        "id": 390988,
        "job_id": 98,
        "project_id": 250,
        "sid": "9",
        "content": "Trang sức H&A – Thế giới Kim Cương",
        "tr": {
            "g": "H&A Jewelry – Diamond World",
            "m": "H&A Jewelry – Diamond World"
        },
        "unit_count": 8,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-26T23:29:15.477Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265502,
            "job_id": 98,
            "source_id": 390988,
            "user_id": 1119094,
            "content": {
                "first_tr": "H&A Jewelry - Diamond World",
                "second_tr": "H&A Jewelry - World of Diamond"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-26T23:29:15.473Z",
            "updated_at": null
        }
    },
    {
        "id": 390989,
        "job_id": 98,
        "project_id": 250,
        "sid": "10",
        "content": "Danh mục cửa hàng – Trang 6 – AEON MALL Long Biên",
        "tr": {
            "g": "Store Directory – Page 6 – AEON MALL Long Bien",
            "m": "Store Catalog – Page 6 – AEON MALL Long Bien"
        },
        "unit_count": 12,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-09T11:49:42.306Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 239798,
            "job_id": 98,
            "source_id": 390989,
            "user_id": 4138730,
            "content": {
                "first_tr": "Store Category - Page 6 - Long Bien AEON MALL",
                "second_tr": "Store Directory - Page 6 - Long Bien AEON MALL"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-09T11:49:42.300Z",
            "updated_at": null
        }
    },
    {
        "id": 390990,
        "job_id": 98,
        "project_id": 250,
        "sid": "13",
        "content": "🏮Vỏ và dây đeo thép không gỉ mạ mạ vàng đồng sang trọng",
        "tr": {
            "g": "🏮Luxury copper-plated stainless steel case and band",
            "m": "🏮Luxurious copper-plated stainless steel case and strap"
        },
        "unit_count": 13,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-17T07:52:38.508Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 264098,
            "job_id": 98,
            "source_id": 390990,
            "user_id": 4336947,
            "content": {
                "first_tr": "🏮Luxury copper gold plated stai nless steel case and band",
                "report_reason_id_list": [
                    18
                ]
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-17T07:52:38.502Z",
            "updated_at": null
        }
    },
    {
        "id": 390991,
        "job_id": 98,
        "project_id": 250,
        "sid": "15",
        "content": "Bước 3: Đến hệ thống tiNi để đổi quà",
        "tr": {
            "g": "Step 3: Go to tiNi system to redeem gifts",
            "m": "Step 3: Go to the tiNi system to redeem gifts"
        },
        "unit_count": 9,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-19T04:30:56.716Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 264558,
            "job_id": 98,
            "source_id": 390991,
            "user_id": 4336947,
            "content": {
                "first_tr": "Step 3: Go to tiNi system to exchange gifts",
                "second_tr": "Step 3: Come to tiNi system to redeem gifts."
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-19T04:30:56.709Z",
            "updated_at": null
        }
    },
    {
        "id": 390992,
        "job_id": 98,
        "project_id": 250,
        "sid": "17",
        "content": "Danh mục cửa hàng – Trang 3 – AEON MALL Long Biên",
        "tr": {
            "g": "Store catalog – Page 3 – AEON MALL Long Bien",
            "m": "Store Catalog – Page 3 – AEON MALL Long Bien"
        },
        "unit_count": 12,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-21T13:11:15.024Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 264824,
            "job_id": 98,
            "source_id": 390992,
            "user_id": 4336947,
            "content": {
                "first_tr": "Store catalog - Page 3 - AEON MALL Long Bien"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 1119094,
            "created_at": "2023-03-21T13:11:15.020Z",
            "updated_at": null
        }
    },
    {
        "id": 390993,
        "job_id": 98,
        "project_id": 250,
        "sid": "18",
        "content": "Trang Chủ - Chùa Điều Ngự - Dieu Ngu Temple",
        "tr": {
            "g": "Home - Dieu Ngu Temple - Dieu Ngu Temple",
            "m": "Home - Dieu Ngu Temple"
        },
        "unit_count": 10,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-20T13:02:32.728Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 264729,
            "job_id": 98,
            "source_id": 390993,
            "user_id": 1119094,
            "content": {
                "first_tr": "Homepage - Dieu Ngu Pagoda - Dieu Ngu Temple",
                "second_tr": "Home Website - Dieu Ngu Pagoda - Dieu Ngu Temple"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4336947,
            "created_at": "2023-03-20T13:02:32.724Z",
            "updated_at": null
        }
    },
    {
        "id": 390994,
        "job_id": 98,
        "project_id": 250,
        "sid": "19",
        "content": "Phim sex Trung Quốc HOT nhất, TOP sex China gái đẹp hàng đầu",
        "tr": {
            "g": "Hottest Chinese sex movies, TOP sexiest Chinese beautiful girls",
            "m": "HOTTEST CHINESE SEX MOVIES, TOP sex China top beautiful girls"
        },
        "unit_count": 13,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-27T12:49:32.077Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265582,
            "job_id": 98,
            "source_id": 390994,
            "user_id": 4139697,
            "content": {
                "first_tr": "The hottest Chinese sex film, TOP beautiful Chinese girls",
                "second_tr": "Hottest Chinese sex movies, TOP sexiest beautiful Chinese girls"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 1119094,
            "created_at": "2023-03-27T12:49:32.061Z",
            "updated_at": null
        }
    },
    {
        "id": 390995,
        "job_id": 98,
        "project_id": 250,
        "sid": "21",
        "content": "Người Tiều (Việt Nam) – Wikipedia tiếng Việt",
        "tr": {
            "g": "Tieu people (Vietnam) - Vietnamese Wikipedia",
            "m": "Qiao people (Vietnam) - Wikipedia, the free encyclopedia"
        },
        "unit_count": 8,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-23T16:36:37.583Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265060,
            "job_id": 98,
            "source_id": 390995,
            "user_id": 4336947,
            "content": {
                "first_tr": "The Teochew people (Vietnam) - Vietnamese Wikipedia"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 1119094,
            "created_at": "2023-03-23T16:36:37.571Z",
            "updated_at": null
        }
    },
    {
        "id": 390996,
        "job_id": 98,
        "project_id": 250,
        "sid": "24",
        "content": "- Hành giả thực hành vô số việc làm cụ thể để tạo thành vô biên phước báo.",
        "tr": {
            "g": "- Practitioners practice innumerable concrete actions to create boundless blessings.",
            "m": "- The practitioner practices a multitude of specific deeds to form boundless blessings."
        },
        "unit_count": 18,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-23T09:36:24.148Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265020,
            "job_id": 98,
            "source_id": 390996,
            "user_id": 4336947,
            "content": {
                "first_tr": "- Monks do innumerable specific work to create unlimited blessings.",
                "second_tr": "- Monks do scads of specific work to create boundless blessings."
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-23T09:36:24.143Z",
            "updated_at": null
        }
    },
    {
        "id": 390997,
        "job_id": 98,
        "project_id": 250,
        "sid": "25",
        "content": "Dù còn nhiều chướng ngại, nhưng hành giả vững lòng thực hành thiền định hướng về mục tiêu Vô ngã.",
        "tr": {
            "g": "Although there are many obstacles, the meditator firmly practices meditation towards the goal of Not-Self.",
            "m": "Although there are many obstacles, the practitioner firmly practices meditation towards the goal of Selflessness."
        },
        "unit_count": 20,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-23T11:56:45.253Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265030,
            "job_id": 98,
            "source_id": 390997,
            "user_id": 4336947,
            "content": {
                "first_tr": "Although there are many obstacles, the monks firmly practice mediation towards the goal of No-self.",
                "second_tr": "Though there are a lot of obstacles, the monks firmly practice mediation towards the goal of No-self."
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-23T11:56:45.248Z",
            "updated_at": null
        }
    },
    {
        "id": 390998,
        "job_id": 98,
        "project_id": 250,
        "sid": "26",
        "content": "- Nghề tốt phải gồm đủ 2 yếu tốt: tạo phước từng ngày và có thời gian tu tập.",
        "tr": {
            "g": "- A good job must include two good elements: creating blessings every day and having time to practice.",
            "m": "- A good profession must include all 2 good elements: creating blessings day by day and having time to practice."
        },
        "unit_count": 19,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-23T11:56:45.253Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265031,
            "job_id": 98,
            "source_id": 390998,
            "user_id": 4336947,
            "content": {
                "first_tr": "- A good job must include these two elements: creating blessing every day and having time to meditate.",
                "second_tr": "- A great job must consist of these two elements: creating blessing every day and having time to meditate."
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-23T11:56:45.248Z",
            "updated_at": null
        }
    },
    {
        "id": 390999,
        "job_id": 98,
        "project_id": 250,
        "sid": "28",
        "content": "- Công phu thiền định được thực hành cẩn thận, được sự nhắc nhở của các bậc Chân tu để có thể tiến đạo.",
        "tr": {
            "g": "- Elaborate meditation is carefully practiced, reminded by True Cultivators to be able to progress.",
            "m": "- Meditation is carefully practiced, reminded by the True Monks to be able to progress."
        },
        "unit_count": 24,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-23T12:14:12.219Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265040,
            "job_id": 98,
            "source_id": 390999,
            "user_id": 4336947,
            "content": {
                "first_tr": "Meditation Kungfu is carefully practiced, reminded by the true Monks to be able to progress.",
                "second_tr": "Meditation Kungfu is carefully practiced, reminded by the true Monks in order to be able to progress."
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-23T12:14:12.215Z",
            "updated_at": null
        }
    },
    {
        "id": 391000,
        "job_id": 98,
        "project_id": 250,
        "sid": "29",
        "content": "Hoàng Thùy Linh – Wikipedia tiếng Việt",
        "tr": {
            "g": "Hoang Thuy Linh – Vietnamese Wikipedia",
            "m": "Hoang Thuy Linh - Wikipedia, the free encyclopedia"
        },
        "unit_count": 7,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-23T12:14:12.219Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265041,
            "job_id": 98,
            "source_id": 391000,
            "user_id": 4336947,
            "content": {
                "first_tr": "Hoang Thuy Linh - VIetnamese Wikipedia"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4139697,
            "created_at": "2023-03-23T12:14:12.215Z",
            "updated_at": null
        }
    },
    {
        "id": 391001,
        "job_id": 98,
        "project_id": 250,
        "sid": "34",
        "content": "Trong dân gian còn truyền tụng câu:",
        "tr": {
            "g": "In folklore, there is a saying:",
            "m": "In folklore also chants:"
        },
        "unit_count": 7,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-25T12:50:27.024Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265226,
            "job_id": 98,
            "source_id": 391001,
            "user_id": 1119094,
            "content": {
                "first_tr": "In folklore, there is still a popular saying that is:",
                "second_tr": "In folklore, a popular saying is currently being spread:"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4138730,
            "created_at": "2023-03-25T12:50:27.017Z",
            "updated_at": null
        }
    },
    {
        "id": 391002,
        "job_id": 98,
        "project_id": 250,
        "sid": "35",
        "content": "Đoàn Nguyên Đức – Wikipedia tiếng Việt",
        "tr": {
            "g": "Doan Nguyen Duc - Vietnamese Wikipedia",
            "m": "Doan Nguyen Duc - Wikipedia, the free encyclopedia"
        },
        "unit_count": 7,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-24T13:14:21.601Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265118,
            "job_id": 98,
            "source_id": 391002,
            "user_id": 4138730,
            "content": {
                "first_tr": "Doan Nguyen Duc - Vietnamese language Wikipedia",
                "second_tr": "Doan Nguyen Duc - Wikipedia of Vietnam"
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4336947,
            "created_at": "2023-03-24T13:14:21.595Z",
            "updated_at": null
        }
    },
    {
        "id": 391003,
        "job_id": 98,
        "project_id": 250,
        "sid": "36",
        "content": "Sau khi tốt nghiệp cấp 3 hệ 12 năm (năm 1982), ông Đức lên Thành phố Hồ Chí Minh thi đại học nhưng thi trượt.",
        "tr": {
            "g": "After graduating from high school for 12 years (in 1982), Mr. Duc went to Ho Chi Minh City to take the university entrance exam but failed.",
            "m": "After graduating from high school 3 for 12 years (in 1982), Mr. Duc went to Ho Chi Minh City to take university exams but failed the exam."
        },
        "unit_count": 25,
        "carded_at": "2023-02-24T09:51:53.608Z",
        "completed_at": null,
        "status": "C",
        "created_at": "2023-02-24T09:51:45.855Z",
        "updated_at": "2023-03-24T13:14:21.601Z",
        "job": {
            "id": 98,
            "client_id": 2,
            "project_id": 250,
            "s3_key": "HT_Apple_viVN-enUS_1088_file1_ADD_MT_230224.xlsx",
            "job_type": "HT",
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "status": "D",
            "created_at": "2023-02-24T09:51:42.877Z",
            "updated_at": "2023-02-24T09:51:53.503Z"
        },
        "project": {
            "id": 250,
            "title": "250_vi-en_A0001_HT - test set",
            "preset_id": 4,
            "src_lang_id": 61,
            "tgt_lang_id": 17,
            "campaign_id": 16,
            "base_points": 16,
            "single_response_point_rate": 0.4,
            "sampling_rate": 0.1,
            "incomplete_points_rate": 0.7,
            "golden_set_fail_limit": 5,
            "golden_set_ratio": 100,
            "card_count": 10,
            "card_type": "SM",
            "parent_project_id": null,
            "period_ms": "6000000",
            "reprocessing_period_ms": "172800000",
            "retry_period_ms": "6000000",
            "objection_period_ms": "86400000",
            "quota_limit_ratio": 20,
            "start_at": null,
            "end_at": "2300-12-30T15:00:00.000Z",
            "status": "N",
            "is_test": "N",
            "unit_type": "W",
            "auto_participate": "N",
            "level_id": 1,
            "allow_priority_level_change": "N",
            "notification_status": "N",
            "completed_at": null,
            "created_at": "2023-02-17T07:53:54.470Z",
            "updated_at": "2023-04-05T08:00:41.489Z",
            "project_preset": {
                "id": 4,
                "preset_name": "HT - test set",
                "resource_type": "HT",
                "input_text_count": 2,
                "created_at": "2022-08-12T00:55:40.843Z",
                "updated_at": null
            }
        },
        "text_translation": {
            "id": 265119,
            "job_id": 98,
            "source_id": 391003,
            "user_id": 4138730,
            "content": {
                "first_tr": "After graduated from 12 graded type high school (1982), Mr.Duc went to Ho Chi Minh City to take the university exam but he failed.",
                "second_tr": "After graduated from 12 years type high school in 1982, Mr. Duc went to Ho Chi Minh City to take the entrance exam but he failed."
            },
            "admin_user_id": null,
            "status": "U",
            "rv_user_id": 4336947,
            "created_at": "2023-03-24T13:14:21.595Z",
            "updated_at": null
        }
    }
]